In [1]:
import numpy as np
print(np.__version__)

1.24.3


### NumPy creating arrays ###

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5]) # || np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in array ##

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays ##

In [10]:
import numpy as np
arr=np.array([1,2,3], ndmin=5)
print(arr)

[[[[[1 2 3]]]]]


## Accessing Array Elements ##

In [15]:
import numpy as np
arr1d=np.array([1,2,3,4,5])
arr2d=np.array([[1,2,3],[4,5,6]])
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1d[0])
print(arr2d[0, 1])
print(arr3d[0,1,2])
print(arr3d[-1,-1,-1])

1
2
6
12


## Array Slicing in 1D ##

In [17]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:4])
print(arr[3:])
print(arr[:3])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4]
[4 5 6 7]
[1 2 3]
[5 6]
[2 4]
[1 3 5 7]


## Array Slicing in 2D ##

In [18]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:3])
print(arr[0:2, 2])


[7 8]
[3 8]


## Datatypes ##

In [25]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array(['apple', 'banana', 'cherry'])
arr3 = np.array([1, 2, 3, 4], dtype='S')
arr4 = np.array([1, 2, 3, 4], dtype='i4')
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)


int32
<U6
|S1
int32


## Converting Datatypes ##

In [28]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## copy ##

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


## view ##

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## Array Shape ##

In [31]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2 = np.array([1, 2, 3, 4], ndmin=5)
print(arr1.shape)
print(arr2.shape)

(2, 4)
(1, 1, 1, 1, 4)


## Reshaping Arrays ##

In [35]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new2d=arr.reshape(4,3)
print(new2d)
print('\n')
new3d=arr.reshape(2,2,3)
print(new3d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Array Iterating ##

In [40]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [39]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


## Enumerate ##

In [41]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3


## Numpy Join ##

In [42]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Numpy Split ##

In [43]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


## Searching Arrays ##

In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


## Sorting Arrays ##

In [45]:
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
print(np.sort(arr)[::-1])

[0 1 2 3]
[3 2 1 0]
